# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iEnglish' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iEnglish
  pod 'BaiduMobStatCodeless' #无埋点SDK

  target 'iEnglishTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iEnglishUITests' do
    # Pods for testing
  end

end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end
